extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern u8 ccm_dl_mossoverlay_rgba16[];
extern u8 ccm_dl_mossbrick_rgba16[];
extern u8 ccm_dl_layer_rgba16[];
extern u8 ccm_dl_mossbrick_ci8[];
extern u8 ccm_dl_mossbrick_pal_rgba16[];
extern u8 ccm_dl_tree_rgba16[];
extern u8 ccm_dl_rockwall_rgba16[];
extern u8 ccm_dl_redflower_rgba16[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_0[315];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_1[52];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_2[356];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_3[28];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_4[68];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_4[];
extern Vtx ccm_dl_f3dlite_material_005Mesh_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_f3dlite_material_005Mesh_mesh_layer_4_vtx_0[346];
extern Gfx ccm_dl_f3dlite_material_005Mesh_mesh_layer_4_tri_0[];
extern Gfx mat_ccm_dl_bricks_001_layer1[];
extern Gfx mat_revert_ccm_dl_bricks_001_layer1[];
extern Gfx mat_ccm_dl_f3dlite_material_002[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_002[];
extern Gfx mat_ccm_dl_f3dlite_material[];
extern Gfx mat_revert_ccm_dl_f3dlite_material[];
extern Gfx mat_ccm_dl_f3dlite_material_004[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_004[];
extern Gfx mat_ccm_dl_f3dlite_material_009[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_009[];
extern Gfx mat_ccm_dl_f3dlite_material_005[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_005[];
extern Gfx ccm_dl_Circle_mesh_layer_1[];
extern Gfx ccm_dl_f3dlite_material_005Mesh_mesh_layer_4[];
extern Gfx ccm_dl_material_revert_render_settings[];
