extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const MacroObject rr_area_1_macro_objs[];
extern u8 rr_dl_brightgrass_ci4[];
extern u8 rr_dl_brightgrass_pal_rgba16[];
extern u8 rr_dl_dirtrock_16color_ci4[];
extern u8 rr_dl_dirtrock_16color_pal_rgba16[];
extern Vtx rr_dl_Plane_mesh_layer_6_vtx_0[718];
extern Gfx rr_dl_Plane_mesh_layer_6_tri_0[];
extern Vtx rr_dl_Plane_mesh_layer_1_vtx_0[223];
extern Gfx rr_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx rr_dl_Plane_001_mesh_layer_6_vtx_0[223];
extern Gfx rr_dl_Plane_001_mesh_layer_6_tri_0[];
extern Gfx mat_rr_dl_grass[];
extern Gfx mat_revert_rr_dl_grass[];
extern Gfx mat_rr_dl_rock[];
extern Gfx mat_revert_rr_dl_rock[];
extern Gfx rr_dl_Plane_mesh_layer_6[];
extern Gfx rr_dl_Plane_mesh_layer_1[];
extern Gfx rr_dl_Plane_001_mesh_layer_6[];
extern Gfx rr_dl_material_revert_render_settings[];
