extern const GeoLayout balloon_geo[];
extern Vtx balloon_visual_mesh_layer_1_vtx_0[48];
extern Gfx balloon_visual_mesh_layer_1_tri_0[];
extern Vtx balloon_visual_mesh_layer_1_vtx_1[16];
extern Gfx balloon_visual_mesh_layer_1_tri_1[];
extern Gfx mat_balloon_f3dlite_material[];
extern Gfx mat_revert_balloon_f3dlite_material[];
extern Gfx mat_balloon_string[];
extern Gfx mat_revert_balloon_string[];
extern Gfx balloon_visual_mesh_layer_1[];
extern Gfx balloon_material_revert_render_settings[];
