extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern u8 wf_dl_Glover_D8B0E62C_0_0_1479930C_ciByRGBA_ci4[];
extern u8 wf_dl_Glover_D8B0E62C_0_0_1479930C_ciByRGBA_pal_rgba16[];
extern u8 wf_dl_mh_brock_o1_rgba16[];
extern u8 wf_dl_Material4_i8[];
extern u8 wf_dl_cs_lawn03_alb_ci8[];
extern u8 wf_dl_cs_lawn03_alb_pal_rgba16[];
extern u8 wf_dl_Grass3_ci8[];
extern u8 wf_dl_Grass3_pal_rgba16[];
extern u8 wf_dl_mossbrick_ci8[];
extern u8 wf_dl_mossbrick_pal_rgba16[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[153];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_1[753];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_2[267];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx wf_dl_bg_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_bg_mesh_layer_1_vtx_0[153];
extern Gfx wf_dl_bg_mesh_layer_1_tri_0[];
extern Vtx wf_dl_bg_mesh_layer_1_vtx_1[753];
extern Gfx wf_dl_bg_mesh_layer_1_tri_1[];
extern Vtx wf_dl_bg_mesh_layer_1_vtx_2[267];
extern Gfx wf_dl_bg_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_0[141];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_1[444];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_2[7];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_2[];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_0[108];
extern Gfx wf_dl_area3_mesh_layer_1_tri_0[];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_1[23];
extern Gfx wf_dl_area3_mesh_layer_1_tri_1[];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_2[48];
extern Gfx wf_dl_area3_mesh_layer_1_tri_2[];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_3[49];
extern Gfx wf_dl_area3_mesh_layer_1_tri_3[];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_4[60];
extern Gfx wf_dl_area3_mesh_layer_1_tri_4[];
extern Vtx wf_dl_area3_mesh_layer_1_vtx_5[9];
extern Gfx wf_dl_area3_mesh_layer_1_tri_5[];
extern Vtx wf_dl_bg_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_bg_001_mesh_layer_1_vtx_0[153];
extern Gfx wf_dl_bg_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_bg_001_mesh_layer_1_vtx_1[753];
extern Gfx wf_dl_bg_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_bg_001_mesh_layer_1_vtx_2[267];
extern Gfx wf_dl_bg_001_mesh_layer_1_tri_2[];
extern Vtx wf_dl_bg2_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_bg2_mesh_layer_1_vtx_0[141];
extern Gfx wf_dl_bg2_mesh_layer_1_tri_0[];
extern Vtx wf_dl_bg2_mesh_layer_1_vtx_1[444];
extern Gfx wf_dl_bg2_mesh_layer_1_tri_1[];
extern Vtx wf_dl_bg2_mesh_layer_1_vtx_2[7];
extern Gfx wf_dl_bg2_mesh_layer_1_tri_2[];
extern Gfx mat_wf_dl_floor[];
extern Gfx mat_revert_wf_dl_floor[];
extern Gfx mat_wf_dl_wall[];
extern Gfx mat_revert_wf_dl_wall[];
extern Gfx mat_wf_dl_roof[];
extern Gfx mat_revert_wf_dl_roof[];
extern Gfx mat_wf_dl_grass[];
extern Gfx mat_revert_wf_dl_grass[];
extern Gfx mat_wf_dl_hedge[];
extern Gfx mat_revert_wf_dl_hedge[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_revert_wf_dl_f3dlite_material_001[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_bg_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_1[];
extern Gfx wf_dl_area3_mesh_layer_1[];
extern Gfx wf_dl_bg_001_mesh_layer_1[];
extern Gfx wf_dl_bg2_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
