extern const GeoLayout ttc_area_1_geo[];
extern const GeoLayout ttc_area_1[];
extern const Collision ttc_area_1_collision[];
extern const MacroObject ttc_area_1_macro_objs[];
extern u8 ttc_dl_yellowbricks_ci4[];
extern u8 ttc_dl_yellowbricks_pal_rgba16[];
extern Vtx ttc_dl_Plane_mesh_layer_1_vtx_0[693];
extern Gfx ttc_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_ttc_dl_brick[];
extern Gfx mat_revert_ttc_dl_brick[];
extern Gfx ttc_dl_Plane_mesh_layer_1[];
extern Gfx ttc_dl_material_revert_render_settings[];
