extern const GeoLayout level_gate_geo[];
extern u8 level_gate_moss_rgba16[];
extern u8 level_gate_mossbrick_ia8[];
extern Vtx level_gate_Circle_002_mesh_layer_1_vtx_cull[8];
extern Vtx level_gate_Circle_002_mesh_layer_1_vtx_0[40];
extern Gfx level_gate_Circle_002_mesh_layer_1_tri_0[];
extern Gfx mat_level_gate_f3dlite_material_010_layer1[];
extern Gfx mat_revert_level_gate_f3dlite_material_010_layer1[];
extern Gfx level_gate_Circle_002_mesh_layer_1[];
extern Gfx level_gate_material_revert_render_settings[];
